### ISSUE TITLE
i or number 9 theory - CONNECTION THEORY

### ISSUE THREAD

**Issue by latsala** [ShaharGottlieb/MasseyRamanujan#7]
If we count each number composed by 315, 3+1+5 we get 9. If we double it to 630, 6+3, we also get 9. If double it again, 1260, we get 9. 2520, 9. 5040, 9. And so on....

This is a connection theory. i vocal is the number 9th letter in the alphabet. It’s the connection letter, that’s why we say AI or iPhone or iPad, or IT, etc. 

This may be useful to Ramanujuan Machine, to make a combination between letters and formulas. Hope so!

thanks
Lautaro
I’m from Argentina and my English it’s not the best.

**Comment by Lytearro** [comment]
Here is 6000 iterations, it breaks on the 7th iteration converting to 18, which is still divisible by 9.. Maybe 6k isn't enough, but not noticing a trend https://raw.githubusercontent.com/Lytearro/theory_i/main/theorem_i.txt

**Comment by Lytearro** [comment]
x = 315 = 9 * 35
I've noticed that all numbers that are multiple of 9 result in their individual added value to that of 9 or a multiple of 9, and this is a rule that transcends, meaning the sum or added digits can subsequently be added together to yield 9 or multiple of 9.

I ran a test of "x = x * 2" 6,000 times and saw this rule still met. I may just be stupid though...

**Comment by ShaharGottlieb** [comment]
every number is divisible 9 by iff the sum of it's digits (in decimal representation) is divisible by 9.
[proof](https://proofwiki.org/wiki/Divisibility_by_9)
